console.log('this is javascript');
let a = window.document;
// a = prompt('this will destroy your computer, type your name');
// a = confirm('Are you sure you want to delete this page?');
a = window.innerHeight;
a = innerWidth;
a = scrollX;
a = scrollY;
a = location.toString();
a = window.history;
console.log(a);